CREATE TABLE IF NOT EXISTS franchise (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS branch (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    franchise_id BIGINT NOT NULL REFERENCES franchise(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS product (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    stock INTEGER NOT NULL,
    branch_id BIGINT NOT NULL REFERENCES branch(id) ON DELETE CASCADE
);

